### ISSUE TITLE
Add MAPC Region and Statewide to download options

### ISSUE THREAD

**Issue by theryankelly** [MAPC/hpp#7] opened 2019-09-03 14:19 UTC
**Describe the Feature**
Add MAPC Region and State to "Municipalities" filter and enable a download option. 

**Background**
The current HPP process is requiring creating two separate spreadsheets to track HPP municipality and one for State wide aggregation.  If the Statewide and MAPC region totals for each could be download in the same file, time would be saved in aggregation.  
I believe the codes for MAPC and Massachusetts are:
352 - MAPC
353 - Mass

**Note:**
- We will have to change the label of the selection box to indicate change.  Maybe: "Municipalities / Region ". 

- Currently the school enrollment file has all, including MAPC and State in any download.  Would like to retain this functionality.

**Comment by atomtay** [comment] 2019-09-06 15:48
Currently MAPC and Massachusetts are showing as options in the server version and you can download reports with that data. However, when you request the same data with the headless version, those two values are ignored (so if you were looking for data in Acton and MAPC, you would only get the Acton information). Looking into the headless discrepancy now.

**Comment by atomtay** [comment] 2019-09-06 20:01
This issue is also fixed on master, but not in production (like #8 ) so I'm closing this issue as well, pending deployment. If the issue is persisting in prod after the next deployment, I'll re-open and re-examine.

**Closed by atomtay** 2019-09-06 20:01 UTC
Labels: enhancement
